package cn.lingcx.demoset.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.lingcx.demoset.model.ChatMessageRecord;

import cn.lingcx.demoset.dao.ChatMessageRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatMessageRecordDaoConfig;

    private final ChatMessageRecordDao chatMessageRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatMessageRecordDaoConfig = daoConfigMap.get(ChatMessageRecordDao.class).clone();
        chatMessageRecordDaoConfig.initIdentityScope(type);

        chatMessageRecordDao = new ChatMessageRecordDao(chatMessageRecordDaoConfig, this);

        registerDao(ChatMessageRecord.class, chatMessageRecordDao);
    }
    
    public void clear() {
        chatMessageRecordDaoConfig.clearIdentityScope();
    }

    public ChatMessageRecordDao getChatMessageRecordDao() {
        return chatMessageRecordDao;
    }

}
